import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  n8nClient: [
    {
      type: 'autogenerated',
      dirName: 'n8n-client',
    },
  ],
  n8nSync: [
    {
      type: 'autogenerated',
      dirName: 'n8n-sync',
    },
  ],
};

export default sidebars;
