import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  about: [{ type: 'autogenerated', dirName: 'about' }],
  api: [{ type: 'autogenerated', dirName: 'api' }],
  example: [{ type: 'autogenerated', dirName: 'example' }],
};

export default sidebars;
